# Generated by Django 5.0.4 on 2024-04-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_shop_state_shop_user_alter_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='prices/{shop.name}/%Y/%m/%d'),
        ),
    ]
