# Generated by Django 5.0.4 on 2024-08-06 21:06

import django.utils.timezone
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_category_shops_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headshot',
            field=versatileimagefield.fields.VersatileImageField(default=django.utils.timezone.now, upload_to='headshots/', verbose_name='Headshot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='headshot_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
