# Generated by Django 5.0.4 on 2024-08-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_category_shops_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='image',
            field=models.URLField(blank=True, verbose_name='Изображение'),
        ),
    ]
