# Generated by Django 5.0.4 on 2024-08-13 17:54

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_category_shops_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image Point of Interest'),
        ),
    ]
