# Generated by Django 5.0.4 on 2024-08-06 21:18

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_product_image_user_headshot_user_headshot_ppoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=versatileimagefield.fields.VersatileImageField(upload_to='user/headshots/%Y/%m/%d/', verbose_name='Headshot'),
        ),
    ]
