# Generated by Django 5.0.4 on 2024-08-08 21:17

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_user_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='orders/media/user/headshots/%Y/%m/%d/', verbose_name='Headshot'),
        ),
    ]
